version: "3.9"

services:
  web:
    build:
      context: ./PatientDashboard
      dockerfile: Dockerfile
    image: patientdashboard:dev
    container_name: patientdashboard-web
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # overrides the SQLite path to the mounted volume
      ConnectionStrings__Default: "Data Source=/app/data/PatientDashboardDatabase.db"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
